quiet: false
disable-version-string: true
with-expecter: true
mockname: "{{.InterfaceName}}"
filename: "mock_{{ .InterfaceName | lower }}.go"
dir: "mocks"
packages:
  github.com/cirius-go/gojen:
    interfaces:
      FileManager:
      ConsoleManager:
