// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package gojen

import (
	"fmt"
	"strings"
)

const (
	// PluralizeTypePlural is a PluralizeType of type plural.
	PluralizeTypePlural PluralizeType = "plural"
	// PluralizeTypeSingular is a PluralizeType of type singular.
	PluralizeTypeSingular PluralizeType = "singular"
	// PluralizeTypeIrregular is a PluralizeType of type irregular.
	PluralizeTypeIrregular PluralizeType = "irregular"
)

var ErrInvalidPluralizeType = fmt.Errorf("not a valid PluralizeType, try [%s]", strings.Join(_PluralizeTypeNames, ", "))

var _PluralizeTypeNames = []string{
	string(PluralizeTypePlural),
	string(PluralizeTypeSingular),
	string(PluralizeTypeIrregular),
}

// PluralizeTypeNames returns a list of possible string values of PluralizeType.
func PluralizeTypeNames() []string {
	tmp := make([]string, len(_PluralizeTypeNames))
	copy(tmp, _PluralizeTypeNames)
	return tmp
}

// PluralizeTypeValues returns a list of the values for PluralizeType
func PluralizeTypeValues() []PluralizeType {
	return []PluralizeType{
		PluralizeTypePlural,
		PluralizeTypeSingular,
		PluralizeTypeIrregular,
	}
}

// String implements the Stringer interface.
func (x PluralizeType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PluralizeType) IsValid() bool {
	_, err := ParsePluralizeType(string(x))
	return err == nil
}

var _PluralizeTypeValue = map[string]PluralizeType{
	"plural":    PluralizeTypePlural,
	"singular":  PluralizeTypeSingular,
	"irregular": PluralizeTypeIrregular,
}

// ParsePluralizeType attempts to convert a string to a PluralizeType.
func ParsePluralizeType(name string) (PluralizeType, error) {
	if x, ok := _PluralizeTypeValue[name]; ok {
		return x, nil
	}
	return PluralizeType(""), fmt.Errorf("%s is %w", name, ErrInvalidPluralizeType)
}

// MarshalText implements the text marshaller method.
func (x PluralizeType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *PluralizeType) UnmarshalText(text []byte) error {
	tmp, err := ParsePluralizeType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// StrategyTrunc is a Strategy of type trunc.
	StrategyTrunc Strategy = "trunc"
	// StrategyAppend is a Strategy of type append.
	StrategyAppend Strategy = "append"
	// StrategyAppendAtLast is a Strategy of type append_at_last.
	StrategyAppendAtLast Strategy = "append_at_last"
	// StrategyIgnore is a Strategy of type ignore.
	StrategyIgnore Strategy = "ignore"
)

var ErrInvalidStrategy = fmt.Errorf("not a valid Strategy, try [%s]", strings.Join(_StrategyNames, ", "))

var _StrategyNames = []string{
	string(StrategyTrunc),
	string(StrategyAppend),
	string(StrategyAppendAtLast),
	string(StrategyIgnore),
}

// StrategyNames returns a list of possible string values of Strategy.
func StrategyNames() []string {
	tmp := make([]string, len(_StrategyNames))
	copy(tmp, _StrategyNames)
	return tmp
}

// StrategyValues returns a list of the values for Strategy
func StrategyValues() []Strategy {
	return []Strategy{
		StrategyTrunc,
		StrategyAppend,
		StrategyAppendAtLast,
		StrategyIgnore,
	}
}

// String implements the Stringer interface.
func (x Strategy) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Strategy) IsValid() bool {
	_, err := ParseStrategy(string(x))
	return err == nil
}

var _StrategyValue = map[string]Strategy{
	"trunc":          StrategyTrunc,
	"append":         StrategyAppend,
	"append_at_last": StrategyAppendAtLast,
	"ignore":         StrategyIgnore,
}

// ParseStrategy attempts to convert a string to a Strategy.
func ParseStrategy(name string) (Strategy, error) {
	if x, ok := _StrategyValue[name]; ok {
		return x, nil
	}
	return Strategy(""), fmt.Errorf("%s is %w", name, ErrInvalidStrategy)
}

// MarshalText implements the text marshaller method.
func (x Strategy) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Strategy) UnmarshalText(text []byte) error {
	tmp, err := ParseStrategy(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
