path: example/go/internal/service/{{ sLower .Domain }}.go
required:
- Domain
name: service
context: {}
select:
- template: |-
    package service

    // {{ sIniCamel .Domain }} service.
    type {{ sIniCamel .Domain }} struct {
    }

    // DO NOT REMOVE THIS COMMENT
    // +gojen:append-template=service
  require:
  - Domain
  strategy: ignore
  confirm: false
- template: |2-

    // {{ sIniCamel .Method }} method of '{{ sIniCamel .Domain }}' service.
    func (s *{{ sIniCamel .Domain }}) {{ sIniCamel .Method }}(ctx context.Context, req *dto.{{ sIniCamel .Method }}{{ sIniCamel .Domain }}Req) (*dto.{{ sIniCamel .Method }}{{ sIniCamel .Domain }}Res, error) {
      panic("not implemented")
    }
  require:
  - Domain
  - Method
  strategy: append
  confirm: true
- template: |-
    // Create new '{{ sIniCamel .Domain }}'.
    func (s *{{ sIniCamel .Domain }}) Create(ctx context.Context, req *dto.Create{{ sIniCamel .Domain }}Req) (*dto.Create{{ sIniCamel .Domain }}Res, error) {
      panic("not implemented")
    }

    // List all '{{ pIniCamel .Domain }}'.
    func (s *{{ sIniCamel .Domain }}) List(ctx context.Context, req *dto.List{{ pIniCamel .Domain }}Req) (*dto.List{{ pIniCamel .Domain }}Res, error) {
      panic("not implemented")
    }

    // Get one of '{{ pIniCamel .Domain }}'.
    func (s *{{ sIniCamel .Domain }}) Get(ctx context.Context, req *dto.Get{{ sIniCamel .Domain }}Req) (*dto.Get{{ sIniCamel .Domain }}Res, error) {
      panic("not implemented")
    }

    // Update one of '{{ pIniCamel .Domain }}'.
    func (s *{{ sIniCamel .Domain }}) Update(ctx context.Context, req *dto.Update{{ sIniCamel .Domain }}Req) (*dto.Update{{ sIniCamel .Domain }}Res, error) {
      panic("not implemented")
    }

    // Delete one of '{{ pIniCamel .Domain }}'.
    func (s *{{ sIniCamel .Domain }}) Delete(ctx context.Context, req *dto.Delete{{ sIniCamel .Domain }}Req) (*dto.Delete{{ sIniCamel .Domain }}Res, error) {
      panic("not implemented")
    }
  require:
  - Domain
  strategy: append
  confirm: true
dependencies: []
description: Generate a service file or append a service method.
